"use client";

import { Plus } from "@phosphor-icons/react";
import { DeveloperCard, DeveloperColorField, DeveloperField, DeveloperHelp, DeveloperSectionHeading, developerInputClassName, developerSecondaryButtonClassName } from "../ui";
import type { ResponsiveMediaPresentation } from "@shared/types/media";

type ContentItem = { title: string; description: string };
type CampaignMedia = { id: string; url: string; kind: string; alt?: string };

export type CampaignV1SectionKey = "lowerSection" | "benefits" | "metrics" | "story" | "showcase" | "testimonial" | "faq" | "finalCta";

export const CAMPAIGN_V1_EDIT_TARGETS = [
  "lowerSection:heading", "lowerSection:map", "lowerSection:form",
  "benefits:heading", "benefits:cards",
  "metrics:heading", "metrics:items",
  "story:image", "story:content", "story:items",
  "showcase:content", "showcase:cards",
  "testimonial:heading", "testimonial:cards",
  "faq:heading", "faq:items",
  "finalCta:image", "finalCta:content",
] as const;

export type CampaignV1EditTarget = (typeof CAMPAIGN_V1_EDIT_TARGETS)[number];

export const campaignV1EditTargetTitle: Record<CampaignV1EditTarget, string> = {
  "lowerSection:heading": "Cobertura B2B", "lowerSection:map": "Cores do mapa", "lowerSection:form": "Formulário B2B",
  "benefits:heading": "Serviços", "benefits:cards": "Cards de serviços",
  "metrics:heading": "Números", "metrics:items": "Indicadores",
  "story:image": "Imagem e conteúdo", "story:content": "Imagem e conteúdo", "story:items": "Diferenciais",
  "showcase:content": "Soluções com foto de fundo", "showcase:cards": "Cards de soluções",
  "testimonial:heading": "Feedbacks", "testimonial:cards": "Cards de feedbacks",
  "faq:heading": "Perguntas frequentes", "faq:items": "Perguntas e respostas",
  "finalCta:image": "Imagem de fundo do CTA", "finalCta:content": "CTA final",
};

export type CampaignV1Sections = {
  lowerSection: { visible: boolean; title: string; description: string; formTitle: string; formDescription: string; submitLabel: string; mapBaseColor: string; mapBranchColor: string; mapBorderColor: string; ctaLabel: string; ctaUrl: string };
  benefits: { visible: boolean; eyebrow: string; title: string; description: string; items: ContentItem[] };
  metrics: { visible: boolean; eyebrow: string; title: string; items: Array<{ value: string; label: string; description: string }> };
  story: { visible: boolean; eyebrow: string; title: string; description: string; image: string; imagePresentation?: ResponsiveMediaPresentation; ctaLabel: string; ctaUrl: string; items: ContentItem[] };
  showcase: { visible: boolean; eyebrow: string; title: string; description: string; backgroundImage: string; backgroundPresentation?: ResponsiveMediaPresentation; ctaLabel: string; ctaUrl: string; items: ContentItem[] };
  testimonial: { visible: boolean; eyebrow: string; title: string; description: string; items: Array<{ name: string; detail: string; quote: string; rating: number }>; quote: string; author: string; role: string };
  faq: { visible: boolean; eyebrow: string; title: string; items: Array<{ question: string; answer: string }> };
  finalCta: { visible: boolean; eyebrow: string; title: string; description: string; backgroundImage: string; backgroundPresentation?: ResponsiveMediaPresentation; ctaLabel: string; ctaUrl: string };
  footer: { brand: string; description: string; phone: string; email: string; legalText: string };
};

function VisibilityToggle({ checked, onChange }: { checked: boolean; onChange: (visible: boolean) => void }) {
  return <label className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-[var(--border)] bg-white px-3 py-1.5 text-xs font-semibold text-[var(--foreground)]"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="size-4 accent-[var(--primary)]" />Exibir seção<DeveloperHelp label="Visibilidade da seção" templateKey="landing-pages.field.section-visibility" /></label>;
}

function MediaSelect({ value, media, emptyLabel, onChange }: { value: string; media: CampaignMedia[]; emptyLabel: string; onChange: (value: string) => void }) {
  return <select value={value} onChange={(event) => onChange(event.target.value)} className={developerInputClassName}><option value="">{emptyLabel}</option>{media.map((item) => <option key={item.id} value={item.url}>{item.alt || item.id}</option>)}</select>;
}

function PairFields({ label, index, item, onChange }: { label: string; index: number; item: ContentItem; onChange: (item: ContentItem) => void }) {
  return <article className="rounded-xl border border-[var(--border)] bg-white p-4"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--muted-foreground)]">{label} {String(index + 1).padStart(2, "0")}</p><DeveloperField label="Título"><input value={item.title} onChange={(event) => onChange({ ...item, title: event.target.value })} className={developerInputClassName} maxLength={100} /></DeveloperField><DeveloperField label="Descrição" className="mt-3"><textarea value={item.description} onChange={(event) => onChange({ ...item, description: event.target.value })} className={developerInputClassName + " min-h-20 resize-y"} maxLength={320} /></DeveloperField></article>;
}

function SectionCard({ active, sectionKey, heading, children }: { active?: CampaignV1SectionKey; sectionKey: CampaignV1SectionKey; heading: React.ReactNode; children: React.ReactNode }) {
  return <DeveloperCard className={active && active !== sectionKey ? "hidden" : undefined}>{heading}{children}</DeveloperCard>;
}

/** Editor do conteúdo abaixo do Hero para o template fechado campaign-v1. */
export function CampaignV1SectionsEditor<T extends CampaignV1Sections>({ landing, media, onChange, section: initialSection, target }: { landing: T; media: CampaignMedia[]; onChange: (update: (current: T) => T) => void; section?: CampaignV1SectionKey; target?: CampaignV1EditTarget }) {
  const imageMedia = media.filter((item) => item.kind === "image");
  const update = <K extends keyof CampaignV1Sections>(key: K, value: CampaignV1Sections[K]) => onChange((current) => ({ ...current, [key]: value }));
  const section = target ? target.split(":")[0] as CampaignV1SectionKey : initialSection;

  return <div className="space-y-5">
    <SectionCard active={section} sectionKey="lowerSection" heading={<DeveloperSectionHeading eyebrow="Template padrão" title="Cobertura e formulário B2B" description="A primeira seção após o Hero apresenta a cobertura nacional e captura uma demanda comercial para a base de Leads." action={<VisibilityToggle checked={landing.lowerSection.visible} onChange={(visible) => update("lowerSection", { ...landing.lowerSection, visible })} />} />}>
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Título da cobertura" helpKey="landing-pages.field.coverage-title"><input value={landing.lowerSection.title} onChange={(event) => update("lowerSection", { ...landing.lowerSection, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Descrição da cobertura" helpKey="landing-pages.field.coverage-description"><textarea value={landing.lowerSection.description} onChange={(event) => update("lowerSection", { ...landing.lowerSection, description: event.target.value })} className={developerInputClassName + " min-h-28 resize-y"} maxLength={900} /></DeveloperField><DeveloperField label="Título do formulário" helpKey="landing-pages.field.b2b-form-title"><input value={landing.lowerSection.formTitle} onChange={(event) => update("lowerSection", { ...landing.lowerSection, formTitle: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Descrição do formulário" helpKey="landing-pages.field.b2b-form-description"><textarea value={landing.lowerSection.formDescription} onChange={(event) => update("lowerSection", { ...landing.lowerSection, formDescription: event.target.value })} className={developerInputClassName + " min-h-24 resize-y"} maxLength={400} /></DeveloperField><DeveloperField label="Texto do botão" helpKey="landing-pages.field.b2b-form-submit" className="md:col-span-2"><input value={landing.lowerSection.submitLabel} onChange={(event) => update("lowerSection", { ...landing.lowerSection, submitLabel: event.target.value })} className={developerInputClassName} maxLength={70} /></DeveloperField></div>
      <div className="mt-5 rounded-xl border border-[var(--border)] bg-slate-50/70 p-4"><p className="text-sm font-semibold text-[var(--foreground)]">Cores do mapa</p><p className="mt-1 text-xs leading-5 text-[var(--color-muted-raw)]">Ajuste a aparência do mapa e das filiais destacadas sem alterar os estados atendidos.</p><div className="mt-4 grid gap-4 md:grid-cols-3"><DeveloperColorField label="Estados sem filial" value={landing.lowerSection.mapBaseColor} onChange={(mapBaseColor) => update("lowerSection", { ...landing.lowerSection, mapBaseColor })} helpKey="landing-pages.field.map-base-color" /><DeveloperColorField label="Estados com filial" value={landing.lowerSection.mapBranchColor} onChange={(mapBranchColor) => update("lowerSection", { ...landing.lowerSection, mapBranchColor })} helpKey="landing-pages.field.map-branch-color" /><DeveloperColorField label="Contornos" value={landing.lowerSection.mapBorderColor} onChange={(mapBorderColor) => update("lowerSection", { ...landing.lowerSection, mapBorderColor })} helpKey="landing-pages.field.map-border-color" /></div></div>
    </SectionCard>

    <SectionCard active={section} sectionKey="benefits" heading={<DeveloperSectionHeading eyebrow="Template padrão" title="Serviços" description="Apresente de um a seis soluções da operação em cards escuros, logo após a cobertura e o formulário B2B." action={<VisibilityToggle checked={landing.benefits.visible} onChange={(visible) => update("benefits", { ...landing.benefits, visible })} />} />}>
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.benefits.eyebrow} onChange={(event) => update("benefits", { ...landing.benefits, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.benefits.title} onChange={(event) => update("benefits", { ...landing.benefits, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Descrição" className="md:col-span-2"><textarea value={landing.benefits.description} onChange={(event) => update("benefits", { ...landing.benefits, description: event.target.value })} className={developerInputClassName + " min-h-24 resize-y"} maxLength={700} /></DeveloperField></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2">{landing.benefits.items.map((item, index) => <PairFields key={index} label="Serviço" index={index} item={item} onChange={(value) => update("benefits", { ...landing.benefits, items: landing.benefits.items.map((current, currentIndex) => currentIndex === index ? value : current) })} />)}</div>
      {landing.benefits.items.length < 6 ? <button type="button" onClick={() => update("benefits", { ...landing.benefits, items: [...landing.benefits.items, { title: "Novo serviço", description: "Explique como esta solução apoia a operação." }] })} className={developerSecondaryButtonClassName + " mt-5"}><Plus size={16} weight="bold" />Adicionar serviço</button> : null}
    </SectionCard>

    <SectionCard active={section} sectionKey="metrics" heading={<DeveloperSectionHeading eyebrow="Template padrão" title="Números" description="Exiba até quatro indicadores logo abaixo dos serviços para demonstrar capacidade, estrutura e experiência." action={<VisibilityToggle checked={landing.metrics.visible} onChange={(visible) => update("metrics", { ...landing.metrics, visible })} />} />}>
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.metrics.eyebrow} onChange={(event) => update("metrics", { ...landing.metrics, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.metrics.title} onChange={(event) => update("metrics", { ...landing.metrics, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField></div>
      <div className="mt-5 grid gap-4 md:grid-cols-3">{landing.metrics.items.map((item, index) => <article key={index} className="rounded-xl border border-[var(--border)] bg-white p-4"><DeveloperField label="Número"><input value={item.value} onChange={(event) => update("metrics", { ...landing.metrics, items: landing.metrics.items.map((current, currentIndex) => currentIndex === index ? { ...current, value: event.target.value } : current) })} className={developerInputClassName} maxLength={40} /></DeveloperField><DeveloperField label="Legenda" className="mt-3"><input value={item.label} onChange={(event) => update("metrics", { ...landing.metrics, items: landing.metrics.items.map((current, currentIndex) => currentIndex === index ? { ...current, label: event.target.value } : current) })} className={developerInputClassName} maxLength={120} /></DeveloperField><DeveloperField label="Descrição" helpKey="landing-pages.field.metric-description" className="mt-3"><textarea value={item.description} onChange={(event) => update("metrics", { ...landing.metrics, items: landing.metrics.items.map((current, currentIndex) => currentIndex === index ? { ...current, description: event.target.value } : current) })} className={developerInputClassName + " min-h-20 resize-y"} maxLength={320} /></DeveloperField></article>)}</div>
      {landing.metrics.items.length < 4 ? <button type="button" onClick={() => update("metrics", { ...landing.metrics, items: [...landing.metrics.items, { value: "04", label: "Novo indicador", description: "Explique por que este número reforça a campanha." }] })} className={developerSecondaryButtonClassName + " mt-5"}><Plus size={16} weight="bold" />Adicionar número</button> : null}
    </SectionCard>

    <SectionCard active={section} sectionKey="story" heading={<DeveloperSectionHeading eyebrow="Template padrão" title="Imagem e conteúdo" description="Exiba uma foto à esquerda e, à direita, um painel sólido com a explicação e os diferenciais da operação." action={<VisibilityToggle checked={landing.story.visible} onChange={(visible) => update("story", { ...landing.story, visible })} />} />}>
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.story.eyebrow} onChange={(event) => update("story", { ...landing.story, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.story.title} onChange={(event) => update("story", { ...landing.story, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Imagem" helpKey="landing-pages.field.story-image"><MediaSelect value={landing.story.image} media={imageMedia} emptyLabel="Sem imagem" onChange={(image) => update("story", { ...landing.story, image })} /></DeveloperField><DeveloperField label="Botão"><input value={landing.story.ctaLabel} onChange={(event) => update("story", { ...landing.story, ctaLabel: event.target.value })} className={developerInputClassName} maxLength={70} /></DeveloperField><DeveloperField label="Descrição" className="md:col-span-2"><textarea value={landing.story.description} onChange={(event) => update("story", { ...landing.story, description: event.target.value })} className={developerInputClassName + " min-h-28 resize-y"} maxLength={900} /></DeveloperField><DeveloperField label="Destino do botão" className="md:col-span-2"><input value={landing.story.ctaUrl} onChange={(event) => update("story", { ...landing.story, ctaUrl: event.target.value })} className={developerInputClassName} maxLength={400} /></DeveloperField></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-2">{landing.story.items.map((item, index) => <PairFields key={index} label="Diferencial" index={index} item={item} onChange={(value) => update("story", { ...landing.story, items: landing.story.items.map((current, currentIndex) => currentIndex === index ? value : current) })} />)}</div>
      {landing.story.items.length < 4 ? <button type="button" onClick={() => update("story", { ...landing.story, items: [...landing.story.items, { title: "Novo diferencial", description: "Explique como este ponto fortalece a operação." }] })} className={developerSecondaryButtonClassName + " mt-5"}><Plus size={16} weight="bold" />Adicionar diferencial</button> : null}
    </SectionCard>

    <SectionCard active={section} sectionKey="showcase" heading={<DeveloperSectionHeading eyebrow="Template padrão" title="Soluções com foto de fundo" description="Apresente até três tipos de operação sobre uma foto de fundo da biblioteca da campanha, logo após a seção de imagem e conteúdo." action={<VisibilityToggle checked={landing.showcase.visible} onChange={(visible) => update("showcase", { ...landing.showcase, visible })} />} />}>
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.showcase.eyebrow} onChange={(event) => update("showcase", { ...landing.showcase, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.showcase.title} onChange={(event) => update("showcase", { ...landing.showcase, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Foto de fundo" helpKey="landing-pages.field.showcase-background"><MediaSelect value={landing.showcase.backgroundImage} media={imageMedia} emptyLabel="Usar fundo sólido" onChange={(backgroundImage) => update("showcase", { ...landing.showcase, backgroundImage })} /></DeveloperField><DeveloperField label="Botão"><input value={landing.showcase.ctaLabel} onChange={(event) => update("showcase", { ...landing.showcase, ctaLabel: event.target.value })} className={developerInputClassName} maxLength={70} /></DeveloperField><DeveloperField label="Descrição" className="md:col-span-2"><textarea value={landing.showcase.description} onChange={(event) => update("showcase", { ...landing.showcase, description: event.target.value })} className={developerInputClassName + " min-h-24 resize-y"} maxLength={700} /></DeveloperField><DeveloperField label="Destino do botão" className="md:col-span-2"><input value={landing.showcase.ctaUrl} onChange={(event) => update("showcase", { ...landing.showcase, ctaUrl: event.target.value })} className={developerInputClassName} maxLength={400} /></DeveloperField></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-3">{landing.showcase.items.map((item, index) => <PairFields key={index} label="Solução" index={index} item={item} onChange={(value) => update("showcase", { ...landing.showcase, items: landing.showcase.items.map((current, currentIndex) => currentIndex === index ? value : current) })} />)}</div>
      {landing.showcase.items.length < 3 ? <button type="button" onClick={() => update("showcase", { ...landing.showcase, items: [...landing.showcase.items, { title: "Nova solução", description: "Explique para qual demanda esta solução é indicada." }] })} className={developerSecondaryButtonClassName + " mt-5"}><Plus size={16} weight="bold" />Adicionar solução</button> : null}
    </SectionCard>

    <SectionCard active={section} sectionKey="testimonial" heading={<DeveloperSectionHeading eyebrow="Template padrão" title="Feedbacks" description="Apresente avaliações autorizadas em cards para reforçar a confiança após a explicação da solução." action={<VisibilityToggle checked={landing.testimonial.visible} onChange={(visible) => update("testimonial", { ...landing.testimonial, visible })} />} />}>
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.testimonial.eyebrow} onChange={(event) => update("testimonial", { ...landing.testimonial, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.testimonial.title} onChange={(event) => update("testimonial", { ...landing.testimonial, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Texto de contexto" helpKey="landing-pages.field.feedback-description" className="md:col-span-2"><textarea value={landing.testimonial.description} onChange={(event) => update("testimonial", { ...landing.testimonial, description: event.target.value })} className={developerInputClassName + " min-h-24 resize-y"} maxLength={900} /></DeveloperField></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-3">{landing.testimonial.items.map((item, index) => <article key={index} className="rounded-xl border border-[var(--border)] bg-white p-4"><DeveloperField label="Nome"><input value={item.name} onChange={(event) => update("testimonial", { ...landing.testimonial, items: landing.testimonial.items.map((current, currentIndex) => currentIndex === index ? { ...current, name: event.target.value } : current) })} className={developerInputClassName} maxLength={100} /></DeveloperField><DeveloperField label="Empresa ou contexto" className="mt-3"><input value={item.detail} onChange={(event) => update("testimonial", { ...landing.testimonial, items: landing.testimonial.items.map((current, currentIndex) => currentIndex === index ? { ...current, detail: event.target.value } : current) })} className={developerInputClassName} maxLength={120} /></DeveloperField><DeveloperField label="Nota" className="mt-3"><select value={item.rating} onChange={(event) => update("testimonial", { ...landing.testimonial, items: landing.testimonial.items.map((current, currentIndex) => currentIndex === index ? { ...current, rating: Number(event.target.value) } : current) })} className={developerInputClassName}>{[5, 4, 3, 2, 1].map((rating) => <option key={rating} value={rating}>{rating} estrela{rating === 1 ? "" : "s"}</option>)}</select></DeveloperField><DeveloperField label="Feedback" helpKey="landing-pages.field.feedback-message" className="mt-3"><textarea value={item.quote} onChange={(event) => update("testimonial", { ...landing.testimonial, items: landing.testimonial.items.map((current, currentIndex) => currentIndex === index ? { ...current, quote: event.target.value } : current) })} className={developerInputClassName + " min-h-24 resize-y"} maxLength={900} /></DeveloperField></article>)}</div>
      {landing.testimonial.items.length < 6 ? <button type="button" onClick={() => update("testimonial", { ...landing.testimonial, items: [...landing.testimonial.items, { name: "Cliente atendido", detail: "Empresa ou operação", quote: "Inclua uma avaliação autorizada.", rating: 5 }] })} className={developerSecondaryButtonClassName + " mt-5"}><Plus size={16} weight="bold" />Adicionar feedback</button> : null}
    </SectionCard>

    <SectionCard active={section} sectionKey="faq" heading={<DeveloperSectionHeading eyebrow="Template padrão" title="Perguntas frequentes" description="Antecipe as dúvidas que podem impedir o contato." action={<VisibilityToggle checked={landing.faq.visible} onChange={(visible) => update("faq", { ...landing.faq, visible })} />} />}>
      <div className="grid gap-3">{landing.faq.items.map((item, index) => <article key={index} className="rounded-xl border border-[var(--border)] bg-white p-4"><DeveloperField label="Pergunta"><input value={item.question} onChange={(event) => update("faq", { ...landing.faq, items: landing.faq.items.map((current, currentIndex) => currentIndex === index ? { ...current, question: event.target.value } : current) })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Resposta" className="mt-3"><textarea value={item.answer} onChange={(event) => update("faq", { ...landing.faq, items: landing.faq.items.map((current, currentIndex) => currentIndex === index ? { ...current, answer: event.target.value } : current) })} className={developerInputClassName + " min-h-24 resize-y"} maxLength={900} /></DeveloperField></article>)}</div>
      {landing.faq.items.length < 8 ? <button type="button" onClick={() => update("faq", { ...landing.faq, items: [...landing.faq.items, { question: "Nova pergunta", answer: "Escreva uma resposta clara." }] })} className={developerSecondaryButtonClassName + " mt-5"}><Plus size={16} weight="bold" />Adicionar pergunta</button> : null}
    </SectionCard>

    <SectionCard active={section} sectionKey="finalCta" heading={<DeveloperSectionHeading eyebrow="Template padrão" title="CTA final" description="Feche a campanha com uma chamada clara para a ação principal." action={<VisibilityToggle checked={landing.finalCta.visible} onChange={(visible) => update("finalCta", { ...landing.finalCta, visible })} />} />}>
      <div className="grid gap-4 md:grid-cols-2"><DeveloperField label="Selo"><input value={landing.finalCta.eyebrow} onChange={(event) => update("finalCta", { ...landing.finalCta, eyebrow: event.target.value })} className={developerInputClassName} maxLength={80} /></DeveloperField><DeveloperField label="Título"><input value={landing.finalCta.title} onChange={(event) => update("finalCta", { ...landing.finalCta, title: event.target.value })} className={developerInputClassName} maxLength={180} /></DeveloperField><DeveloperField label="Imagem de fundo"><MediaSelect value={landing.finalCta.backgroundImage} media={imageMedia} emptyLabel="Usar fundo sólido" onChange={(backgroundImage) => update("finalCta", { ...landing.finalCta, backgroundImage })} /></DeveloperField><DeveloperField label="Botão"><input value={landing.finalCta.ctaLabel} onChange={(event) => update("finalCta", { ...landing.finalCta, ctaLabel: event.target.value })} className={developerInputClassName} maxLength={70} /></DeveloperField><DeveloperField label="Descrição" className="md:col-span-2"><textarea value={landing.finalCta.description} onChange={(event) => update("finalCta", { ...landing.finalCta, description: event.target.value })} className={developerInputClassName + " min-h-24 resize-y"} maxLength={700} /></DeveloperField><DeveloperField label="Destino do botão" className="md:col-span-2"><input value={landing.finalCta.ctaUrl} onChange={(event) => update("finalCta", { ...landing.finalCta, ctaUrl: event.target.value })} className={developerInputClassName} maxLength={400} /></DeveloperField></div>
    </SectionCard>
  </div>;
}
