"use client";

import { Plus } from "@phosphor-icons/react";
import { DeveloperColorField, DeveloperField, DeveloperHelp, DeveloperSectionHeading, developerInputClassName, developerSecondaryButtonClassName } from "../ui";
import { MediaPlacementEditor } from "../MediaPlacementEditor";
import type { CampaignV1Sections } from "./CampaignV1SectionsEditor";

export type CampaignV1EditTarget =
  | "lowerSection:heading" | "lowerSection:map" | "lowerSection:form"
  | "benefits:heading" | "benefits:cards"
  | "metrics:heading" | "metrics:items"
  | "showcase:content" | "showcase:cards"
  | "story:image" | "story:content" | "story:items"
  | "testimonial:heading" | "testimonial:cards"
  | "faq:heading" | "faq:items"
  | "finalCta:content" | "finalCta:image";

export const CAMPAIGN_V1_EDIT_TARGETS: readonly CampaignV1EditTarget[] = [
  "lowerSection:heading", "lowerSection:map", "lowerSection:form", "benefits:heading", "benefits:cards",
  "metrics:heading", "metrics:items", "showcase:content", "showcase:cards", "story:image", "story:content",
  "story:items", "testimonial:heading", "testimonial:cards", "faq:heading", "faq:items", "finalCta:content", "finalCta:image",
];

export const campaignV1EditTargetTitle: Record<CampaignV1EditTarget, string> = {
  "lowerSection:heading": "Título da cobertura", "lowerSection:map": "Mapa de cobertura", "lowerSection:form": "Formulário B2B",
  "benefits:heading": "Introdução dos serviços", "benefits:cards": "Cards de serviços",
  "metrics:heading": "Introdução dos números", "metrics:items": "Indicadores da campanha",
  "showcase:content": "Mensagem das soluções", "showcase:cards": "Cards de soluções",
  "story:image": "Imagem da seção", "story:content": "Conteúdo da seção", "story:items": "Diferenciais da seção",
  "testimonial:heading": "Introdução dos feedbacks", "testimonial:cards": "Cards de feedbacks",
  "faq:heading": "Introdução das perguntas", "faq:items": "Perguntas e respostas",
  "finalCta:content": "Chamada final", "finalCta:image": "Imagem do CTA final",
};

type CampaignMedia = { id: string; url: string; kind: string; alt?: string };

function Toggle({ checked, onChange }: { checked: boolean; onChange: (visible: boolean) => void }) {
  return <label className="inline-flex min-h-9 items-center gap-2 rounded-lg border border-[var(--border)] bg-white px-3 py-1.5 text-xs font-semibold text-[var(--foreground)]"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="size-4 accent-[var(--primary)]" />Exibir seção<DeveloperHelp label="Visibilidade da seção" templateKey="landing-pages.field.section-visibility" /></label>;
}

function Panel({ target, description, visible, children }: { target: CampaignV1EditTarget; description: string; visible?: { checked: boolean; onChange: (value: boolean) => void }; children: React.ReactNode }) {
  return <section><DeveloperSectionHeading eyebrow="Edição da seção" title={campaignV1EditTargetTitle[target]} description={description} action={visible ? <Toggle checked={visible.checked} onChange={visible.onChange} /> : undefined} />{children}</section>;
}

function TextControl({ label, value, onChange, maxLength, multiline = false, helpKey }: { label: string; value: string; onChange: (value: string) => void; maxLength: number; multiline?: boolean; helpKey?: string }) {
  return <DeveloperField label={label} helpKey={helpKey}>{multiline ? <textarea value={value} onChange={(event) => onChange(event.target.value)} className={`${developerInputClassName} min-h-24 resize-y`} maxLength={maxLength} /> : <input value={value} onChange={(event) => onChange(event.target.value)} className={developerInputClassName} maxLength={maxLength} />}</DeveloperField>;
}

function TextPair({ item, index, label, onChange }: { item: { title: string; description: string }; index: number; label: string; onChange: (value: { title: string; description: string }) => void }) {
  return <article className="rounded-xl border border-[var(--border)] bg-slate-50/70 p-4"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--color-muted-raw)]">{label} {String(index + 1).padStart(2, "0")}</p><div className="grid gap-3"><TextControl label="Título" value={item.title} onChange={(title) => onChange({ ...item, title })} maxLength={100} /><TextControl label="Descrição" value={item.description} onChange={(description) => onChange({ ...item, description })} maxLength={320} multiline /></div></article>;
}

/** Cada alvo corresponde a um lápis da prévia, mantendo o diálogo curto e contextual. */
export function CampaignV1FocusedSectionEditor<T extends CampaignV1Sections>({ landing, media, onChange, target }: { landing: T; media: CampaignMedia[]; onChange: (update: (current: T) => T) => void; target: CampaignV1EditTarget }) {
  const imageMedia = media.filter((item) => item.kind === "image");
  const storyMedia = media.filter((item) => item.kind === "image" || item.kind === "video");
  const update = <K extends keyof CampaignV1Sections>(key: K, value: CampaignV1Sections[K]) => onChange((current) => ({ ...current, [key]: value }));
  const selectImage = (value: string, emptyLabel: string, onSelect: (url: string) => void, helpKey?: string) => <DeveloperField label="Imagem" helpKey={helpKey}><select value={value} onChange={(event) => onSelect(event.target.value)} className={developerInputClassName}><option value="">{emptyLabel}</option>{imageMedia.map((item) => <option key={item.id} value={item.url}>{item.alt || item.id}</option>)}</select></DeveloperField>;
  const selectStoryMedia = (value: string, onSelect: (url: string) => void) => <DeveloperField label="Imagem ou vídeo" helpKey="landing-pages.field.story-image"><select value={value} onChange={(event) => onSelect(event.target.value)} className={developerInputClassName}><option value="">Sem mídia</option>{storyMedia.map((item) => <option key={item.id} value={item.url}>{item.kind === "video" ? "Vídeo — " : "Imagem — "}{item.alt || item.id}</option>)}</select></DeveloperField>;
  const placementEditor = (label: string, src: string, value: CampaignV1Sections["story"]["imagePresentation"], onChange: (presentation: NonNullable<CampaignV1Sections["story"]["imagePresentation"]>) => void, frameAspectRatio: string) => {
    const selected = media.find((item) => item.url === src);
    return <MediaPlacementEditor label={label} src={src} alt={selected?.alt} mediaType={selected?.kind === "video" ? "video" : "image"} value={value} onChange={onChange} frameAspectRatio={frameAspectRatio} />;
  };

  switch (target) {
    case "lowerSection:heading": return <Panel target={target} description="Ajuste o título e o texto acima do mapa e do formulário." visible={{ checked: landing.lowerSection.visible, onChange: (visible) => update("lowerSection", { ...landing.lowerSection, visible }) }}><div className="grid gap-4"><TextControl label="Título da cobertura" value={landing.lowerSection.title} onChange={(title) => update("lowerSection", { ...landing.lowerSection, title })} maxLength={180} helpKey="landing-pages.field.coverage-title" /><TextControl label="Descrição da cobertura" value={landing.lowerSection.description} onChange={(description) => update("lowerSection", { ...landing.lowerSection, description })} maxLength={900} multiline helpKey="landing-pages.field.coverage-description" /></div></Panel>;
    case "lowerSection:map": return <Panel target={target} description="Defina somente as cores do mapa. Os estados com filial continuam definidos pelo contrato canônico."><div className="grid gap-4 md:grid-cols-3"><DeveloperColorField label="Estados sem filial" value={landing.lowerSection.mapBaseColor} onChange={(mapBaseColor) => update("lowerSection", { ...landing.lowerSection, mapBaseColor })} helpKey="landing-pages.field.map-base-color" /><DeveloperColorField label="Estados com filial" value={landing.lowerSection.mapBranchColor} onChange={(mapBranchColor) => update("lowerSection", { ...landing.lowerSection, mapBranchColor })} helpKey="landing-pages.field.map-branch-color" /><DeveloperColorField label="Contornos" value={landing.lowerSection.mapBorderColor} onChange={(mapBorderColor) => update("lowerSection", { ...landing.lowerSection, mapBorderColor })} helpKey="landing-pages.field.map-border-color" /></div></Panel>;
    case "lowerSection:form": return <Panel target={target} description="Edite apenas o card comercial que fica ao lado do mapa."><div className="grid gap-4"><TextControl label="Título do formulário" value={landing.lowerSection.formTitle} onChange={(formTitle) => update("lowerSection", { ...landing.lowerSection, formTitle })} maxLength={180} helpKey="landing-pages.field.b2b-form-title" /><TextControl label="Descrição do formulário" value={landing.lowerSection.formDescription} onChange={(formDescription) => update("lowerSection", { ...landing.lowerSection, formDescription })} maxLength={400} multiline helpKey="landing-pages.field.b2b-form-description" /><TextControl label="Texto do botão" value={landing.lowerSection.submitLabel} onChange={(submitLabel) => update("lowerSection", { ...landing.lowerSection, submitLabel })} maxLength={70} helpKey="landing-pages.field.b2b-form-submit" /></div></Panel>;
    case "benefits:heading": return <Panel target={target} description="Edite a chamada que apresenta os cards de serviços." visible={{ checked: landing.benefits.visible, onChange: (visible) => update("benefits", { ...landing.benefits, visible }) }}><div className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><TextControl label="Selo" value={landing.benefits.eyebrow} onChange={(eyebrow) => update("benefits", { ...landing.benefits, eyebrow })} maxLength={80} /><TextControl label="Título" value={landing.benefits.title} onChange={(title) => update("benefits", { ...landing.benefits, title })} maxLength={180} /></div><TextControl label="Descrição" value={landing.benefits.description} onChange={(description) => update("benefits", { ...landing.benefits, description })} maxLength={700} multiline /></div></Panel>;
    case "benefits:cards": return <Panel target={target} description="Organize somente os cards escuros exibidos nesta área."><div className="grid gap-4 lg:grid-cols-2">{landing.benefits.items.map((item, index) => <TextPair key={index} item={item} index={index} label="Serviço" onChange={(value) => update("benefits", { ...landing.benefits, items: landing.benefits.items.map((current, currentIndex) => currentIndex === index ? value : current) })} />)}</div>{landing.benefits.items.length < 6 ? <button type="button" onClick={() => update("benefits", { ...landing.benefits, items: [...landing.benefits.items, { title: "Novo serviço", description: "Explique este serviço." }] })} className={`${developerSecondaryButtonClassName} mt-5`}><Plus size={16} weight="bold" />Adicionar serviço</button> : null}</Panel>;
    case "metrics:heading": return <Panel target={target} description="Ajuste a chamada opcional acima dos números." visible={{ checked: landing.metrics.visible, onChange: (visible) => update("metrics", { ...landing.metrics, visible }) }}><div className="grid gap-4 md:grid-cols-2"><TextControl label="Selo" value={landing.metrics.eyebrow} onChange={(eyebrow) => update("metrics", { ...landing.metrics, eyebrow })} maxLength={80} /><TextControl label="Título" value={landing.metrics.title} onChange={(title) => update("metrics", { ...landing.metrics, title })} maxLength={180} /></div></Panel>;
    case "metrics:items": return <Panel target={target} description="Edite cada indicador sem misturar a introdução da seção."><div className="grid gap-3 md:grid-cols-2">{landing.metrics.items.map((item, index) => <article key={index} className="rounded-xl border border-[var(--border)] bg-slate-50/70 p-4"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--color-muted-raw)]">Indicador {String(index + 1).padStart(2, "0")}</p><div className="grid gap-3"><TextControl label="Número" value={item.value} onChange={(value) => update("metrics", { ...landing.metrics, items: landing.metrics.items.map((current, currentIndex) => currentIndex === index ? { ...current, value } : current) })} maxLength={40} /><TextControl label="Legenda" value={item.label} onChange={(label) => update("metrics", { ...landing.metrics, items: landing.metrics.items.map((current, currentIndex) => currentIndex === index ? { ...current, label } : current) })} maxLength={120} /><TextControl label="Descrição" value={item.description} onChange={(description) => update("metrics", { ...landing.metrics, items: landing.metrics.items.map((current, currentIndex) => currentIndex === index ? { ...current, description } : current) })} maxLength={320} multiline helpKey="landing-pages.field.metric-description" /></div></article>)}</div>{landing.metrics.items.length < 4 ? <button type="button" onClick={() => update("metrics", { ...landing.metrics, items: [...landing.metrics.items, { value: "04", label: "Novo indicador", description: "Explique por que este número reforça a campanha." }] })} className={`${developerSecondaryButtonClassName} mt-4`}><Plus size={16} weight="bold" />Adicionar número</button> : null}</Panel>;
    case "showcase:content": return <Panel target={target} description="Edite a imagem de fundo, a mensagem e o CTA das soluções." visible={{ checked: landing.showcase.visible, onChange: (visible) => update("showcase", { ...landing.showcase, visible }) }}><div className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><TextControl label="Selo" value={landing.showcase.eyebrow} onChange={(eyebrow) => update("showcase", { ...landing.showcase, eyebrow })} maxLength={80} /><TextControl label="Título" value={landing.showcase.title} onChange={(title) => update("showcase", { ...landing.showcase, title })} maxLength={180} /><DeveloperField label="Imagem de fundo" helpKey="landing-pages.field.showcase-background"><select value={landing.showcase.backgroundImage} onChange={(event) => update("showcase", { ...landing.showcase, backgroundImage: event.target.value })} className={developerInputClassName}><option value="">Usar fundo sólido</option>{imageMedia.map((item) => <option key={item.id} value={item.url}>{item.alt || item.id}</option>)}</select></DeveloperField><TextControl label="Botão" value={landing.showcase.ctaLabel} onChange={(ctaLabel) => update("showcase", { ...landing.showcase, ctaLabel })} maxLength={70} /></div>{placementEditor("o fundo das soluções", landing.showcase.backgroundImage, landing.showcase.backgroundPresentation, (backgroundPresentation) => update("showcase", { ...landing.showcase, backgroundPresentation }), "2,9:1")}<TextControl label="Descrição" value={landing.showcase.description} onChange={(description) => update("showcase", { ...landing.showcase, description })} maxLength={700} multiline /><TextControl label="Destino do botão" value={landing.showcase.ctaUrl} onChange={(ctaUrl) => update("showcase", { ...landing.showcase, ctaUrl })} maxLength={400} /></div></Panel>;
    case "showcase:cards": return <Panel target={target} description="Edite somente os cards que acompanham a chamada de soluções."><div className="grid gap-4 lg:grid-cols-3">{landing.showcase.items.map((item, index) => <TextPair key={index} item={item} index={index} label="Solução" onChange={(value) => update("showcase", { ...landing.showcase, items: landing.showcase.items.map((current, currentIndex) => currentIndex === index ? value : current) })} />)}</div>{landing.showcase.items.length < 3 ? <button type="button" onClick={() => update("showcase", { ...landing.showcase, items: [...landing.showcase.items, { title: "Nova solução", description: "Explique para qual demanda ela é indicada." }] })} className={`${developerSecondaryButtonClassName} mt-5`}><Plus size={16} weight="bold" />Adicionar solução</button> : null}</Panel>;
    case "story:image": return <Panel target={target} description="Escolha a imagem ou o vídeo da coluna esquerda. Vídeos são reproduzidos com controles e podem receber um poster na biblioteca.">{selectStoryMedia(landing.story.image, (image) => update("story", { ...landing.story, image }))}{placementEditor("a coluna de mídia", landing.story.image, landing.story.imagePresentation, (imagePresentation) => update("story", { ...landing.story, imagePresentation }), "1:1")}</Panel>;
    case "story:content": return <Panel target={target} description="Edite o painel textual da coluna direita." visible={{ checked: landing.story.visible, onChange: (visible) => update("story", { ...landing.story, visible }) }}><div className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><TextControl label="Selo" value={landing.story.eyebrow} onChange={(eyebrow) => update("story", { ...landing.story, eyebrow })} maxLength={80} /><TextControl label="Título" value={landing.story.title} onChange={(title) => update("story", { ...landing.story, title })} maxLength={180} /><TextControl label="Botão" value={landing.story.ctaLabel} onChange={(ctaLabel) => update("story", { ...landing.story, ctaLabel })} maxLength={70} /><TextControl label="Destino do botão" value={landing.story.ctaUrl} onChange={(ctaUrl) => update("story", { ...landing.story, ctaUrl })} maxLength={400} /></div><TextControl label="Descrição" value={landing.story.description} onChange={(description) => update("story", { ...landing.story, description })} maxLength={900} multiline /></div></Panel>;
    case "story:items": return <Panel target={target} description="Gerencie somente os diferenciais do painel da direita."><div className="grid gap-4 lg:grid-cols-2">{landing.story.items.map((item, index) => <TextPair key={index} item={item} index={index} label="Diferencial" onChange={(value) => update("story", { ...landing.story, items: landing.story.items.map((current, currentIndex) => currentIndex === index ? value : current) })} />)}</div>{landing.story.items.length < 4 ? <button type="button" onClick={() => update("story", { ...landing.story, items: [...landing.story.items, { title: "Novo diferencial", description: "Explique como este ponto fortalece a operação." }] })} className={`${developerSecondaryButtonClassName} mt-5`}><Plus size={16} weight="bold" />Adicionar diferencial</button> : null}</Panel>;
    case "testimonial:heading": return <Panel target={target} description="Edite a chamada antes dos depoimentos autorizados." visible={{ checked: landing.testimonial.visible, onChange: (visible) => update("testimonial", { ...landing.testimonial, visible }) }}><div className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><TextControl label="Selo" value={landing.testimonial.eyebrow} onChange={(eyebrow) => update("testimonial", { ...landing.testimonial, eyebrow })} maxLength={80} /><TextControl label="Título" value={landing.testimonial.title} onChange={(title) => update("testimonial", { ...landing.testimonial, title })} maxLength={180} /></div><TextControl label="Texto de contexto" value={landing.testimonial.description} onChange={(description) => update("testimonial", { ...landing.testimonial, description })} maxLength={900} multiline helpKey="landing-pages.field.feedback-description" /></div></Panel>;
    case "testimonial:cards": return <Panel target={target} description="Edite os cards de avaliações sem alterar a chamada institucional."><div className="grid gap-3 md:grid-cols-2">{landing.testimonial.items.map((item, index) => <article key={index} className="rounded-xl border border-[var(--border)] bg-slate-50/70 p-4"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--color-muted-raw)]">Feedback {String(index + 1).padStart(2, "0")}</p><div className="grid gap-3"><TextControl label="Nome" value={item.name} onChange={(name) => update("testimonial", { ...landing.testimonial, items: landing.testimonial.items.map((current, currentIndex) => currentIndex === index ? { ...current, name } : current) })} maxLength={100} /><TextControl label="Empresa ou contexto" value={item.detail} onChange={(detail) => update("testimonial", { ...landing.testimonial, items: landing.testimonial.items.map((current, currentIndex) => currentIndex === index ? { ...current, detail } : current) })} maxLength={120} /><DeveloperField label="Nota"><select value={item.rating} onChange={(event) => update("testimonial", { ...landing.testimonial, items: landing.testimonial.items.map((current, currentIndex) => currentIndex === index ? { ...current, rating: Number(event.target.value) } : current) })} className={developerInputClassName}>{[5, 4, 3, 2, 1].map((rating) => <option key={rating} value={rating}>{rating} estrela{rating === 1 ? "" : "s"}</option>)}</select></DeveloperField><TextControl label="Feedback" value={item.quote} onChange={(quote) => update("testimonial", { ...landing.testimonial, items: landing.testimonial.items.map((current, currentIndex) => currentIndex === index ? { ...current, quote } : current) })} maxLength={900} multiline helpKey="landing-pages.field.feedback-message" /></div></article>)}</div>{landing.testimonial.items.length < 6 ? <button type="button" onClick={() => update("testimonial", { ...landing.testimonial, items: [...landing.testimonial.items, { name: "Cliente atendido", detail: "Empresa ou operação", quote: "Inclua uma avaliação autorizada.", rating: 5 }] })} className={`${developerSecondaryButtonClassName} mt-4`}><Plus size={16} weight="bold" />Adicionar feedback</button> : null}</Panel>;
    case "faq:heading": return <Panel target={target} description="Edite a chamada que introduz as dúvidas." visible={{ checked: landing.faq.visible, onChange: (visible) => update("faq", { ...landing.faq, visible }) }}><div className="grid gap-4 md:grid-cols-2"><TextControl label="Selo" value={landing.faq.eyebrow} onChange={(eyebrow) => update("faq", { ...landing.faq, eyebrow })} maxLength={80} /><TextControl label="Título" value={landing.faq.title} onChange={(title) => update("faq", { ...landing.faq, title })} maxLength={180} /></div></Panel>;
    case "faq:items": return <Panel target={target} description="Edite as perguntas e respostas abertas pelo visitante."><div className="grid gap-3">{landing.faq.items.map((item, index) => <article key={index} className="rounded-xl border border-[var(--border)] bg-slate-50/70 p-4"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.16em] text-[var(--color-muted-raw)]">Pergunta {String(index + 1).padStart(2, "0")}</p><div className="grid gap-3"><TextControl label="Pergunta" value={item.question} onChange={(question) => update("faq", { ...landing.faq, items: landing.faq.items.map((current, currentIndex) => currentIndex === index ? { ...current, question } : current) })} maxLength={180} /><TextControl label="Resposta" value={item.answer} onChange={(answer) => update("faq", { ...landing.faq, items: landing.faq.items.map((current, currentIndex) => currentIndex === index ? { ...current, answer } : current) })} maxLength={900} multiline /></div></article>)}</div>{landing.faq.items.length < 8 ? <button type="button" onClick={() => update("faq", { ...landing.faq, items: [...landing.faq.items, { question: "Nova pergunta", answer: "Escreva uma resposta clara." }] })} className={`${developerSecondaryButtonClassName} mt-4`}><Plus size={16} weight="bold" />Adicionar pergunta</button> : null}</Panel>;
    case "finalCta:content": return <Panel target={target} description="Edite somente a chamada e a ação antes do rodapé." visible={{ checked: landing.finalCta.visible, onChange: (visible) => update("finalCta", { ...landing.finalCta, visible }) }}><div className="grid gap-4"><div className="grid gap-4 md:grid-cols-2"><TextControl label="Selo" value={landing.finalCta.eyebrow} onChange={(eyebrow) => update("finalCta", { ...landing.finalCta, eyebrow })} maxLength={80} /><TextControl label="Título" value={landing.finalCta.title} onChange={(title) => update("finalCta", { ...landing.finalCta, title })} maxLength={180} /><TextControl label="Botão" value={landing.finalCta.ctaLabel} onChange={(ctaLabel) => update("finalCta", { ...landing.finalCta, ctaLabel })} maxLength={70} /><TextControl label="Destino do botão" value={landing.finalCta.ctaUrl} onChange={(ctaUrl) => update("finalCta", { ...landing.finalCta, ctaUrl })} maxLength={400} /></div><TextControl label="Descrição" value={landing.finalCta.description} onChange={(description) => update("finalCta", { ...landing.finalCta, description })} maxLength={700} multiline /></div></Panel>;
    case "finalCta:image": return <Panel target={target} description="Escolha somente a imagem de fundo do CTA final.">{selectImage(landing.finalCta.backgroundImage, "Usar fundo sólido", (backgroundImage) => update("finalCta", { ...landing.finalCta, backgroundImage }), "landing-pages.field.final-cta-image")}{placementEditor("o CTA final", landing.finalCta.backgroundImage, landing.finalCta.backgroundPresentation, (backgroundPresentation) => update("finalCta", { ...landing.finalCta, backgroundPresentation }), "4,9:1")}</Panel>;
  }
}
